--Consultar as encomendas que ja chegaram:
SELECT f.NOME_MARCA AS FORNECEDOR_MARCA, r.CODIGO_FR AS PRODUTO_MARCA,
	r.NOME_PD, e.NOME_PD, e.CODIGO_EN, e.DATA_ENVIO
	FROM FORNECEDOR f
	JOIN PRODUTO r ON f.NOME_MARCA = r.NOME_MARCA
	JOIN ENCOMENDA e ON r.NOME_PD = e.NOME_PD
	WHERE e.DATA_ENVIO != NULL;




