--Consultar as encomendas que ja chegaram:
SELECT f.NOME_MARCA AS FORNECEDOR_MARCA, r.CODIGO_FR AS PRODUTO_MARCA,
	r.NOME_PD, e.NOME_PD, e.CODIGO_EN, e.DATA_ENVIO
	FROM FORNECEDOR f
	JOIN PRODUTO r ON f.NOME_MARCA = r.NOME_MARCA
	JOIN ENCOMENDA e ON r.NOME_PD = e.NOME_PD
	WHERE e.DATA_ENVIO IS NOT NULL;

--Consultar as encomendas que ainda nao chegaram:
SELECT f.NOME_MARCA AS FORNECEDOR_MARCA, r.CODIGO_FR AS PRODUTO_MARCA,
	r.NOME_PD, e.NOME_PD, e.CODIGO_EN, e.DATA_ENVIO
	FROM FORNECEDOR f
	JOIN PRODUTO r ON f.NOME_MARCA = r.NOME_MARCA
	JOIN ENCOMENDA e ON r.NOME_PD = e.NOME_PD
	WHERE e.DATA_ENVIO IS NULL;
--Consultar os produtos roubados--
SELECT * FROM ROUBADO;
	
--Consultar os produtos danificados--
SELECT * FROM DANIFICADO;

--consulta os produtos vencidos--
SELECT r.NOME_PD, r.CODIGO_PD, v.VALIDADE, r.VALIDADE
	FROM PRODUTO r
	JOIN VALIDADE_OUT v ON v.NOME_PD = r.NOME_PD
	WHERE v.VALIDADE > CURRENT_DATE;




